kind: pipeline
name: 应用发布
platform:
  os: linux
  arch: amd64
steps:
  - name: 代码编译
    image: maven:3.6.3-jdk-8
    volumes:
      - name: cache
        path: /root/.m2
    commands:
      - mvn clean install -DskipTests=true
  - name: 构建镜像
    image: plugins/docker
    volumes:
      - name: docker
        path: /var/run/docker.sock
    settings:
      username: qq478502053
      password: hou987656
      registry: registry.cn-beijing.aliyuncs.com
      repo: registry.cn-beijing.aliyuncs.com/rock_chao/${DRONE_REPO_NAME}
      tags: ${DRONE_COMMIT}
    when:
      event: [ promote ]
  - name: 应用部署
    image: appleboy/drone-ssh
    settings:
      host: 47.93.48.50
      username: root
      password: Hou987656
      port: 22
      script:
        - echo "connect server..."
        - docker run -d --name droneDemo -p 8099:8080 registry.cn-beijing.aliyuncs.com/rock_chao/drone:${DRONE_COMMIT}
        - echo "run ..."
    when:
      event: [ promote ]
volumes:
  - name: cache
    host:
      path: /tmp/cache/${DRONE_REPO_NAME}/.m2
  - name: docker
    host:
      path: /var/run/docker.sock